apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ahud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ahud
    app.kubernetes.io/part-of: byoc-app-hfzf
  name: ahud
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ahud
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ahud
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-kdbo-tenant/byoc-app-hfzf/ahud@sha256:7f1b7f869a6cde1a0d8682a9c7ba913c2de0faab530eb7f974e0f4c8957d4bf8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
