apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ahud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ahud
    app.kubernetes.io/part-of: byoc-app-hfzf
  name: ahud
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ahud
status:
  loadBalancer: {}
