apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ahud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ahud
    app.kubernetes.io/part-of: byoc-app-hfzf
  name: ahud
spec:
  rules:
  - host: ahud-byoc-kdbo-tenant.apps.e3fb04123f03a74bb921.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ahud
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
